### PR TITLE
Fix extra nonzero call for chained comparisons #1190

### PR DESCRIPTION
**Pull request by sizeoftank**
Skip last branch.

### CODE REVIEW

**Comment by kmod** [comment]
Looks great!  Tiny thing though -- would you mind removing the TODO right above the code you added?  The todo is referring to the issue you are solving here :)

**Comment by sizeoftank** [comment]
OK, I will remove the TODO when I back to home tonight :-)

**Comment by sizeoftank** [comment]
@kmod updated.

**Comment by kmod** [comment]
Awesome thanks!

In case you're interested, if you put "fixes #1190" in the PR / commit description, github will notice that and automatically close the issue when the PR gets merged :)

**Pull request merged**
