### PR TITLE
Document that we need libssl-dev

### PR DESCRIPTION
**Pull request by rntz**

### CODE REVIEW

**Comment by kmod** [comment]
Do we need to add this to the cmake instructions too?  I guess it's already included in the travis build but I'm not sure how.

**Comment by rntz** [comment]
I actually don't know anything about building with cmake. When I try following the instructions it breaks on my machine.

**Comment by rntz** [comment]
@kmod Ok, this should be mergeable now.

**Comment by corona10** [comment]
I experienced build-broken with 'can not find -lcrypto -lssl' message. 
I resolved it by installing libssl-dev

**Comment by kmod** [comment]
Cool, thanks :)

**Pull request merged**
