### PR TITLE
cmake configure script

### PR DESCRIPTION
**Pull request by dagar**
This generates config.h in the output directory that contains a define for the sizeof(pyston::BoxedDict).

The files cmake/CheckTypeSize.c.in and cmake/CheckTypeSize.cmake are pulled from cmake 3 (BSD licensed) for compatibility with older Ubuntu.

### CODE REVIEW

**Comment by aisk** [comment]
Cool ~!

**Comment by kmod** [comment]
Cool!  Can we get comments in those files about where they came from?

**Comment by dagar** [comment]
Comments added. Eventually LLVM will require cmake >= 3 and then they can be removed.

**Comment by kmod** [comment]
awesome, thanks :)

**Comment by aisk** [comment]
Hi @dagar , I build pyston in yosemite, and got a failed and a warning in cmake process:
```
....
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of pyston::BoxedDict
-- Check size of pyston::BoxedDict - failed
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.9.1")
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   basic_test
   descr_test
   slots_test

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/asaka/pyston-build
```

And got an error in ninja build:

```
...
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Sphinx disabled.
stat /Users/asaka/pyston/bindings/go/conftest.go: no such file or directory
-- Go bindings disabled, need at least Go 1.2.
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- Could NOT find OCaml (missing:  OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Targeting X86
-- Clang version: 3.7.0
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   basic_test
   descr_test
   slots_test

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/asaka/pyston-build
[30/2746] Building C object from_cpython/CMakeFiles/FROM_CPYTHON.dir/Modules/posixmodule.c.o
FAILED: CCACHE_CPP2=yes /usr/local/bin/ccache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang  -DDEFAULT_PYTHON_MAJOR_VERSION=2 -DDEFAULT_PYTHON_MICRO_VERSION=6 -DDEFAULT_PYTHON_MINOR_VERSION=7 -DLLVMREV=230300 -DNVALGRIND -DTHREADING_USE_GIL=1 -DTHREADING_USE_GRWL=0 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Qunused-arguments -fcolor-diagnostics -Wall -Wextra -Werror -Wreturn-type -Wno-sign-compare -Wno-unused -Wno-sign-compare -Wno-unused-parameter -fno-omit-frame-pointer -Wno-missing-field-initializers -Wno-tautological-compare -Wno-type-limits -Wno-unused-result -Wno-strict-aliasing -O3 -DNDEBUG -I/Users/asaka/pyston_deps/llvm-trunk/include -Illvm/include -I/Users/asaka/pyston/from_cpython/Include -MMD -MT from_cpython/CMakeFiles/FROM_CPYTHON.dir/Modules/posixmodule.c.o -MF from_cpython/CMakeFiles/FROM_CPYTHON.dir/Modules/posixmodule.c.o.d -o from_cpython/CMakeFiles/FROM_CPYTHON.dir/Modules/posixmodule.c.o   -c /Users/asaka/pyston/from_cpython/Modules/posixmodule.c
/Users/asaka/pyston/from_cpython/Modules/posixmodule.c:21:16: error: weak identifier 'statvfs' never declared [-Werror]
#  pragma weak statvfs
               ^
/Users/asaka/pyston/from_cpython/Modules/posixmodule.c:22:16: error: weak identifier 'fstatvfs' never declared [-Werror]
#  pragma weak fstatvfs
               ^
2 errors generated.
[30/2746] Building C object from_cpython/CMakeFiles/FROM_CPYTHON.dir/Modules/_sre.c.o
ninja: build stopped: subcommand failed.
```

**Comment by kmod** [comment]
I can't really comment on the the cmake warnings, but the posixmodule.c errors are "expected" since we don't do the configuration process that CPython expects.  ie we have a hardcoded `pyconfig.h` which we copy as-needed from the pyconfig.h we get on a linux machine, so I'm sure we're enabling features that are not available on other platforms.  You can try commenting out all the `#define HAVE_FOO` lines in pyconfig.h to see if it gets farther, but I still doubt it will get very far :)

**Comment by dagar** [comment]
@aisk - Here's a working cmake build system for cpython 2.7
https://github.com/davidsansome/python-cmake-buildsystem

We could use their entire pyconfig.h generation or just pick what we need.
https://github.com/davidsansome/python-cmake-buildsystem/blob/master/cmake/config-unix/pyconfig.h.in

I'll look into that cmake warning.

**Pull request merged**
