### PR TITLE
Quick fix for issue #1083

### PR DESCRIPTION
**Pull request by corona10**
* Quick fix for issue #1083
* use _PyObject_GetDictPtr of cpython implementation
* `std::sort(allDerefVarsAndInfo.begin(), allDerefVarsAndInfo.end(), derefComparator);` to remove functor and use lambda expression

now pyston can fully execute `test/cpython/test_datetime.py`

### CODE REVIEW

**Comment by kmod** [comment]
We have some differences from CPython in how we represent attributes, so we have to be very careful with how we implement _PyObject_GetDictPtr.  Specifically, we have objects which have attributes which aren't stored as dicts (we store them as hidden-class-based attributes aka "hcattrs"), and for those objects I'm not sure if there's any reasonable way to handle a call to _PyObject_GetDictPtr.

I think maybe the most straightforward solution for now is to add a `RELEASE_ASSERT(!tp->instancesHaveHCAttrs())` assert before the code that looks at tp_dictoffset.  I think the code you copied over should be correct for the non-hcattrs case, but it will get the hcattrs case wrong so we need to add the check first.

**Comment by corona10** [comment]
@kmod Thanks! I don't know whether we can solve the problem but I find out more about the problem. I modify it as use Cpython implementation when it has `HCAttrs` if not it throws non implementation error.
so now pyston can not execute `test/cpython/test_datetime.py` fully until this problem resolved. :disappointed: 

And, Is threre any problem about fixing issue #1083 and remove functor `derefComparator`??

**Comment by kmod** [comment]
Awesome, thanks!

Personally I lean away from making changes like switching derefComparator if it wasn't hurting us at all, but I won't argue against doing the cleanup if you are motivated :)

**Comment by corona10** [comment]
@kmod Thanks~

**Pull request merged**
