### PR TITLE
implement recursive printing of set and tuples.

### PR DESCRIPTION
**Pull request by corona10**
#689

implement recursive printing of set and tuples.

### CODE REVIEW

**Comment by kmod** [comment]
Can we get some tests?  The tuple case is a bit hard to reproduce but I think this works:
```python
class C(object):
    def __init__(self):
        self.t = (self,)
    def __repr__(self):
        return repr(self.t)
print repr(C())
```

I think the set one can be triggered using the same test case but switching the tuple to a set.

**Comment by corona10** [comment]
@kmod 
in my guess set can be infinate set theorically but Cpython implementation prohibit this kind of set.

**Comment by kmod** [comment]
Ah ok nice, catch, didn't realize that we currently allowed hashing sets :)  Can we have a test for that though?

Also, I think we can test the set-recursion case using the same thing as the tuple test but with a set:
```python
class C(object):
    def __init__(self):
        self.t = set([self])
    def __repr__(self):
        return repr(self.t)
print repr(C())
```

**Comment by kmod** [comment]
looks good!  just a minor comment -- in the future let's avoid using `# should_error` and we could probably just include these tests in one of the existing test files.

**Comment by fhaseen419-byte** [comment]
Hello what you say about github

**Pull request merged**
