### PR TITLE
BoxedWrapper optimizations

### PR DESCRIPTION
**Pull request by undingen**
```
           django_template3.py             2.8s (4)             2.8s (4)  -0.2%
                 pyxl_bench.py             2.2s (4)             2.2s (4)  -0.7%
     sqlalchemy_imperative2.py             2.8s (4)             2.7s (4)  -1.0%
                       geomean                 2.6s                 2.6s  -0.6%
```

### CODE REVIEW

**Comment by kmod** [comment]
nice :)  not a big deal either way, but is there a reason to have the 1-arg version take the extra always-NULL parameter?

**Comment by undingen** [comment]
I removed the unused always zero arg - should now be ready for merging

**Comment by undingen** [comment]
Oh I forgot that I now have commit access, I merged this one in because removing the NULL arg was pretty trivial change and you already reviewed the other changes before - hope that's fine.

**Comment by kmod** [comment]
yep sgtm :)

**Pull request merged**
