### PR TITLE
handle the situation which provide a directory to pyston

### LINKED ISSUE #800: Running Pyston on a directory doesn't do the right thing
for example `./pyston_dbg /`

Looks like it's supposed to look for a `__main__` module, and throw an exception if it doesn't find one.  We exit with code 0; not sure if we looked for a main module or not.

### PR DESCRIPTION
**Pull request by Daetalus**
closes #800

### CODE REVIEW

**Comment by kmod** [comment]
hey, is this ready to review?

**Comment by kmod** [comment]
awesome :)  should have mentioned though -- can we get a test for this?  We can add a subdirectory inside test/tests, and then create a test file that tries to run it.

**Comment by Daetalus** [comment]
Will include in next generic commit. My original plan is use subprogress to get output. Is that is a correct way?

**Comment by kmod** [comment]
yep, sounds good.  dash_c.py seems like a decent starting point.

**Comment by Daetalus** [comment]
Thanks!

**Pull request merged**
