### PR TITLE
Add missing tp_as_mapping

### PR DESCRIPTION
**Pull request by sizeoftank**
Add list tp_as_mapping for issue #1197

### CODE REVIEW

**Comment by sizeoftank** [comment]
` pyc_stress_test ` failed in CI, is it something wrong with these commits? @kmod

**Comment by kmod** [comment]
It's just a long test and it's been bumping up against the test timeout.  I snuck in https://github.com/dropbox/pyston/pull/1289/commits/10f9ec7b4f0ebdcad65fa972f58cc9ae14053d20 which reduces the amount of work that this test does so this should hopefully go away.  Sorry about that!

I'm going to close+reopen this so that the CI picks up the new master revision.

**Comment by sizeoftank** [comment]
Thanks for your feedback
Is it necessary to restart the previous commit?  I see that ` pyopenssl_test `  failed and  ` cffi_test ` time out.

**Comment by kmod** [comment]
Awesome thanks!

**Pull request merged**
