### PR TITLE
Dictionary comparisons

### PR DESCRIPTION
**Pull request by kmod**
@sizeoftank's #1271 but with the commits re-separated

### CODE REVIEW

**Comment by sizeoftank** [comment]
Oh ! unfortunately... 
pyopenssl_test.py failed.

**Comment by kmod** [comment]
This is a flaky test we imported from pyopenssl -- see https://github.com/pyca/pyopenssl/issues/266

They get two timestamps and make sure the seconds match :(  It's come up a few times so we'll want to find a way around it, but at least it's not something with this PR :)

**Comment by sizeoftank** [comment]
oh, so it restart a new ci check and run successed ?
and this PR ready to merge?

**Comment by kmod** [comment]
Yep I just reran the CI and it passed :)

Thanks for the change!

**Pull request merged**
