### PR TITLE
clang-3.7 support

### PR DESCRIPTION
**Pull request by kmod**
This is a continuation of #1019 and [dean0x7d/clang37_fixes](https://github.com/dean0x7d/pyston/commits/clang37_fixes).

### CODE REVIEW

**Comment by dean0x7d** [comment]
Sure, but the comarison was `< (1L << 31) - 1` not `<=  (1L << 31) - 1`.

**Comment by undingen** [comment]
Oh sorry you are of course correct. I think I should grab some coffee... :blush:

**Comment by kmod** [comment]
Hmm it seems like the original comparisons were wrong, I'm going to go ahead and change it.

**Comment by kmod** [comment]
Hey Marius can you look at the new commit I added?  I think it's good but if we messed it up once we should check twice before changing it :)

**Comment by undingen** [comment]
lgtm, I checked with the instruction manual I could not see why we can't include the MAX_INT.

**Pull request merged**
