### PR TITLE
Fixes the issue of del_unpacking #294

### PR DESCRIPTION
**Pull request by ssarangi**
Recursively unpack all the elements of List and Tuple to add new AST delete nodes and prevent addition of empty nodes coming from List & Tuple.

### CODE REVIEW

**Comment by ssarangi** [comment]
I will update the test to be expected pass for this.

**Comment by kmod** [comment]
"Unexpected success" is probably the best way to fail the tests :)  If you wouldn't mind, it'd be nice if you could squash the commits into a single commit while you're at it.  thanks for taking this!

**Comment by ssarangi** [comment]
Absolutely... :) I will update the test and send a single commit..

**Comment by ssarangi** [comment]
Closing this one since I sent a new pull request

**Pull request closed without merging**
