### PR TITLE
travis try enabling apt cache

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Overall saves about 80 seconds per build. Doesn't exactly resolve PR #258, but it's something...

**Comment by undingen** [comment]
Maybe we could enable ccache and enable the travis ci cache for it? (to speed up the llvm build)

**Comment by dagar** [comment]
All caching is supposed to be only available for the paid tiers. Based on their documentation I didn't expect this to even work.

**Comment by undingen** [comment]
Oh yeah, I should have read the the whole page instead of only a sentence... :-1: (or at least the first one :bowtie:)

**Comment by dagar** [comment]
Let's try anyway. #357

**Comment by kmod** [comment]
cool, thanks :)

**Pull request merged**
