### PR TITLE
quick fix for support long type in range() function

### PR DESCRIPTION
**Pull request by corona10**
quick fix for support long type in range() function

but it needs some re-factoring..

### CODE REVIEW

**Comment by kmod** [comment]
Hmm, maybe you could try using `PyLong_AsLong()`?  This function handles both longs and ints and converts them to an unboxed long.  Since this is a CAPI function being called from a Pyston function, you'd have to call `checkAndThrowCAPIException()` after each call to it.

**Comment by corona10** [comment]
hmm i used  asSignedLong(BoxedLong* para);

for example

 if(isSubclass(start->cls, long_cls))
 {
      istop = asSignedLong((BoxedLong*)start);
 }

**Comment by corona10** [comment]
okay i will try it

**Comment by corona10** [comment]
but is there any way to get pyobject from box to use PyLong_AsLong() function?
I know that i am less famillar with pyston source code.
but i can not find the way

**Comment by kmod** [comment]
PyObject* is a typedef for Box*, so you can just pass it through :)

**Comment by corona10** [comment]
I re-factored the code after your reviewing it looks more clearly and cool

**Comment by kmod** [comment]
Looks good :)  Can you squash the changes and undo the extraneous whitespace change?  Also, let's not call RELEASE_ASSERT on the types any more -- PyLong_AsLong does the proper error checking and will raise any issues as a Python error instead of crashing the process :P

**Comment by corona10** [comment]
okay i fix it

**Comment by kmod** [comment]
Merged in 0e111b5f967b8c8a0a50f052eb16407800d08171

**Comment by kmod** [comment]
thanks for the contribution!

**Pull request closed without merging**
