### PR TITLE
Eval

### PR DESCRIPTION
**Pull request by tjhance**
v0 of `eval`

Can read global variables, but not local variables yet. It can't write either kind.

Should either get that stuff or working or add in some asserts so it will fail properly in those cases.

It was useful to add the `AST_Expression`, which is an alternative to `AST_Module` in the Official Python Grammar:

```
mod = Module(stmt* body)
	    | Interactive(stmt* body)
	    | Expression(expr body)
```

So there are, like, three node types that are variants of the name `expr` but that's just how the grammar is, I guess.

### CODE REVIEW

**Comment by tjhance** [comment]
rebased and fixed the build

**Comment by kmod** [comment]
lgtm, but can we split up the eval test so that the whole thing doesn't have to be marked with `expected: fail`?  Also the build is failing, I think due to a missed conflict (I added a new call to `parse()`).

**Comment by tjhance** [comment]
OK, I commented out most of the `eval_test.py` which isn't working.

I also got it to read local variables.

**Comment by tjhance** [comment]
okay, the build should be fixed now, although it could be cleaned up a bit

**Comment by tjhance** [comment]
I modified `getLocals()` to include variables passed in from closures. This unlocks a few more achievements in `eval_test.py`.

**Comment by kmod** [comment]
awesome!

**Pull request merged**
