### PR TITLE
get iobench.py working

### PR DESCRIPTION
**Pull request by toshok**
a few small additions to get iobench.py working.

The `__doc__` change (46773ef) is wrong for a couple reasons, the biggest of which is that it's only set in the interpreter: The `-n` command line flag results in no doc strings.  Where should this go instead?  `wrapFunction`?

### CODE REVIEW

**Comment by undingen** [comment]
Concerning the file.seek() and file.tell(): I have locally added the cpython implementation of this two functions, (besides being much more complicated) it looks like they handle ```f_skipnextlf```. I'm not sure if this is something we need to support?(https://gist.github.com/undingen/627b09dd6f908638bcc2 )

**Comment by toshok** [comment]
I'd prefer the cpython implementations, definitely.  I'll remove that
src/runtime change from my PR, and we can gate my PR on when your change
makes it in.

**Comment by undingen** [comment]
Ok I have added the change (slightly modified) to #376.

**Comment by kmod** [comment]
Ok, I merged #376

**Comment by toshok** [comment]
this change should be ready to go other than the fact that iobench.py dirties up the pyston/ directory with temp files.  similar to 4e9effb, maybe we need makefile bits to run minibenchmarks in tempdirs.

**Pull request merged**
