### PR TITLE
jemalloc

### PR DESCRIPTION
**Pull request by dagar**
@toshok - I assume you want to build a specific version of jemalloc and use it everywhere as a generic malloc?

### CODE REVIEW

**Comment by toshok** [comment]
yeah, I tried both 3.6 and the dev branch in git and 3.6 was faster (which
was a surprise to jasone - dev branch is due to be released as 4.0 sometime
in the near future).  Definitely 3.6 until/unless I can help him figure out
what's going on.

**Comment by toshok** [comment]
in the link line i see `-Wl,-rpath,/home/travis/pyston-build/jemalloc/lib -ljemalloc` but no `-L/home/travis-pyston-build/jemalloc/lib`

**Comment by dagar** [comment]
@toshok added now. In a previous version I tried linking the full path to the lib, but I can't get cmake to properly understand the dependency within the ExternalProject. Oh well.
This isn't really the proper cmake way to link and set rpath, but it's good enough unless someone is planning an msvc port in the near future.

**Comment by dagar** [comment]
To see jemalloc stats

    MALLOC_CONF=stats_print:true ./pyston

**Comment by toshok** [comment]
hey @dagar, there's a good chance this travis-ci failure was due to other changes from when you rebased.  any chance you could rebase off master and force push again?

**Comment by dagar** [comment]
Rebased, but now some cpython tests are timing out in the clang debug build (new).

               getattr_exceptions.py    FAILED (Timed out)
                           dash_m.py    FAILED (Timed out)
                          io_test.py    FAILED (Timed out)
                  thread_spawning.py    FAILED (Timed out)
                     inspect_test.py    FAILED (Timed out)
                     logging_test.py    FAILED (Timed out)
             multiprocessing_test.py    FAILED (Timed out)
                          os_test.py    FAILED (Timed out)
                           dash_c.py    FAILED (Timed out)

**Comment by dagar** [comment]
The Pyston debug build compiles jemalloc with --enable-debug, would could be the cause. Is it worth increasing the test timeout to keep this?

               --enable-debug
               Enable assertions and validation code.  This incurs a substantial
               performance hit, but is very useful during application development.
               Implies --enable-ivsalloc.

**Comment by toshok** [comment]
I don't think it's worth it.  having stats enabled (which are be default) is enough.

**Comment by kmod** [comment]
Agreed, sounds like an interesting flag, but probably more useful for manual debugging than the automated testing.  I was thinking maybe we could have the debug checks turned on by default but have travis-ci turn them off, but it sounds like the overhead might be too high for even that.

**Comment by dagar** [comment]
Removed  --enable-debug and the build is passing.

**Comment by kmod** [comment]
This is pretty awesome :)

```
       django_template.py             3.9s (2)             3.6s (2)  -7.8%
            pyxl_bench.py             3.6s (2)             3.4s (2)  -5.1%
sqlalchemy_imperative2.py             4.8s (2)             4.4s (2)  -9.1%
                  geomean                 4.1s                 3.8s  -7.3%
```

**Comment by kmod** [comment]
One minor thing -- I had to still `git submodule update --init` manually, since the "Re-running CMake" step failed:
```
ninja: Entering directory `/mnt/kmod/pyston/build/Debug'
[1/1] Re-running CMake...
FAILED: /usr/bin/cmake -H/mnt/kmod/pyston -B/mnt/kmod/pyston/build/Debug
-- found ccache /usr/bin/ccache
-- found the gold linker /usr/bin/ld.gold
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1426 (message):
  error: no download info for 'libjemalloc' -- please specify
  existing/non-empty SOURCE_DIR or one of URL, CVS_REPOSITORY and CVS_MODULE,
  SVN_REPOSITORY, GIT_REPOSITORY, HG_REPOSITORY or DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1805 (_ep_add_download_command)
  CMakeLists.txt:83 (ExternalProject_Add)
```

**Comment by dagar** [comment]
Based on previous conversations I didn't think you wanted cmake handling git submodule update --init?
For example you're trying different versions of libunwind, libpypa, etc and you don't want it to automatically checkout the gitmodule version when building.

**Comment by kmod** [comment]
yeah I probably said that :)  I guess I'm just seeing that we have libjemalloc depending on gitsubmodules, which I think doesn't quite work out since we need to have already done the submodule checkout at cmake time (ie before ninja time).

**Pull request merged**
