### PR TITLE
build jemalloc

### PR DESCRIPTION
**Pull request by Dundee**
If not build, error is raised:

ninja: error: 'jemalloc/lib/libjemalloc.a', needed by 'pyston', missing and no known rule to make it

### CODE REVIEW

**Comment by kmod** [comment]
Oh interesting, what version of cmake do you have (`cmake --version`)?  We have some hacks for jemalloc to workaround some bugs in cmake, but they might interact poorly with some versions of cmake.

**Comment by Dundee** [comment]
I have cmake 3.3.2

**Comment by kmod** [comment]
I think #1003 should fix this, would you mind pulling and trying again?

**Comment by Dundee** [comment]
Yes, it works now. Thanks!

**Pull request closed without merging**
