### PR TITLE
[WIP]Let GCC 5 happy and update the CPython test notes

### PR DESCRIPTION
**Pull request by Daetalus**

### CODE REVIEW

**Comment by corona10** [comment]
I  hope this PR merged ASAP. I could not built pyston on Ubuntu 16.04 LTS by this issue.

**Comment by kmod** [comment]
I missed the "wip" in the title :P  this looks great, thanks!

**Comment by Daetalus** [comment]
Thanks. I thought this is not hurry. 😄

**Comment by kmod** [comment]
I was running into the same exact issues so it made sense to merge it :)

**Pull request merged**
