### PR TITLE
Generator: don't generate the traceback for the StopIteration exc when the generator is exiting back to a hasnext call.

### PR DESCRIPTION
**Pull request by undingen**
This is a small perf improvement for django-template.py: took  7.4ms for last iteration from 8.2ms

### CODE REVIEW

**Comment by undingen** [comment]
@toshok mmmh just realized that with the incremental traceback change this should be an non issue?

**Comment by toshok** [comment]
it's not as big an improvement with the incremental traceback change, but it's still a win:

before:
```
took  6.8ms for last iteration

real	0m6.058s
user	0m5.880s
sys	0m0.171s
```

after:
```
took  6.6ms for last iteration

real	0m5.934s
user	0m5.750s
sys	0m0.171s
```

so :+1: here :)

**Comment by kmod** [comment]
Good idea :)  In trying to understand the generator control flow, I discovered we don't handle this correctly (we assert):

```python
def f():
    yield 1/0

g = f()

try:
    g.next()
except Exception as e:
    print type(e), e

try:
    g.next()
except Exception as e:
    print type(e), e
```

**Comment by undingen** [comment]
yeah understanding the control flow of the generator stuff is really hard :-(.
I can fix you example if you like - should be in the same lines of code I just touched.

**Comment by kmod** [comment]
Turns out there wasn't much to do -- #589

**Comment by undingen** [comment]
:-)

**Pull request merged**
