### PR TITLE
Rewrite unaryop and property get

### PR DESCRIPTION
**Pull request by undingen**
```
      django_template3.py             3.3s (4)             3.2s (4)  -0.9%
            pyxl_bench.py             2.7s (4)             2.7s (4)  -0.6%
sqlalchemy_imperative2.py             3.1s (4)             3.1s (4)  -1.8%
                  geomean                 3.0s                 3.0s  -1.1%
```

### CODE REVIEW

**Comment by kmod** [comment]
lgtm -- I restarted the failed build (looks like it hit a new sporadic failure we've been seeing).

**Comment by undingen** [comment]
I will rebase it in a moment failed again because of the submodule changes...

**Comment by kmod** [comment]
oh that's weird that it half-picked-up the new changes.

**Comment by undingen** [comment]
this should be ready

**Comment by kmod** [comment]
nice :)

**Pull request merged**
