### PR TITLE
add docker

### PR DESCRIPTION
**Pull request by KrishMunot**

### CODE REVIEW

**Comment by kmod** [comment]
This looks great, but would you mind adding some sort of doc on how to use it?

**Comment by KrishMunot** [comment]
Yes, I will add it soon. 
Can you merge this while we are at it? 
Thanks! :smiley:

**Comment by corona10** [comment]
@kmod It looks like same docker code when I made PR as #1148 but it looks good. :-)

**Comment by kmod** [comment]
Hi @KrishMunot, would you mind cherry-picking corona10's original commit, rather than copying the file and creating a new commit?  You should be able to do it with
```
git fetch origin eae40ee9
git cherry-pick eae40ee9
```

Could you also add a small doc somewhere?  I'm pretty hesitant to merge something like this without at least a tiny amount of documentation, since otherwise we/I won't remember what's going on with it and it is likely to just get removed.  Even just corona10's two lines of instruction from #1099 would be great to have in the readme.

**Comment by kmod** [comment]
I'm going to close this and we can keep discussing on #1099

**Pull request closed without merging**
