### PR TITLE
add versions of llvm's DenseMap/DenseSet which take allocator functors

### PR DESCRIPTION
**Pull request by toshok**
This change didn't seem to help django-template.py performance much, so I was pretty down on it, but it seems to help some microbenchmarks, and gets us -2.4% on geomean:

```
              pyston (calibration)                      :    1.0s baseline: 1.0 (-0.1%)
              pyston django_migrate.py                  :    3.6s baseline: 3.9 (-8.2%)
              pyston interp2.py                         :    6.1s baseline: 6.1 (+0.2%)
              pyston raytrace.py                        :    6.4s baseline: 6.5 (-1.6%)
              pyston nbody.py                           :    8.1s baseline: 8.6 (-6.0%)
              pyston fannkuch.py                        :    7.3s baseline: 7.3 (+0.0%)
              pyston chaos.py                           :   19.7s baseline: 20.1 (-2.1%)
              pyston fasta.py                           :    5.3s baseline: 5.5 (-4.4%)
              pyston pidigits.py                        :    5.7s baseline: 5.6 (+1.8%)
              pyston richards.py                        :    2.9s baseline: 3.0 (-1.6%)
              pyston deltablue.py                       :    2.1s baseline: 2.2 (-1.8%)
              pyston (geomean-8999)                     :    5.6s baseline: 5.7 (-2.4%)
```

This seems like something we could/should upstream to llvm as well

### CODE REVIEW

**Comment by toshok** [comment]
ouch, between then and now things have changed slightly it seems.  here's the current comparison against master:

```
                           88eedd39ce0745f6e0:  4e8cb3ff80777d463d:
       django_template.py             4.7s (2)             6.8s (2)  +44.9%
            pyxl_bench.py             3.9s (2)             5.4s (2)  +36.8%
sqlalchemy_imperative2.py             5.1s (2)             7.0s (2)  +39.2%
        django_migrate.py             1.8s (2)             3.2s (2)  +76.4%
      virtualenv_bench.py             7.8s (2)             7.8s (2)  +0.0%
                  geomean                 4.2s                 5.8s  +37.2%
```

**Comment by kmod** [comment]
hmm could you try running the numbers again?  Not sure why they would be so off, but I'm not seeing the regression when I try running it.

`fetch = +refs/pull/*/head:refs/pr/*` ftw

**Comment by toshok** [comment]
yeah, no clue... just re-ran and got this:

```
                           88eedd39ce0745f6e0:  4e8cb3ff80777d463d:
       django_template.py             4.7s (2)             4.6s (4)  -3.1%
            pyxl_bench.py             3.9s (2)             3.7s (4)  -4.1%
sqlalchemy_imperative2.py             5.1s (2)             4.9s (4)  -2.3%
        django_migrate.py             1.8s (2)             1.8s (4)  -1.4%
      virtualenv_bench.py             7.8s (2)             7.8s (4)  -0.6%
                  geomean                 4.2s                 4.1s  -2.3%
```

**Comment by undingen** [comment]
I tried this with current head (https://github.com/undingen/pyston/commits/densemaps_up): I get this numbers:
```
                           ea3daebf08d007db3e:  3befefeed9670a9005:
      django_template3.py             3.3s (4)             3.2s (4)  -1.3%
            pyxl_bench.py             2.8s (4)             2.7s (4)  -3.2%
sqlalchemy_imperative2.py             3.2s (4)             3.2s (4)  -1.2%
                  geomean                 3.1s                 3.0s  -1.9%
```

But the sqlalchemy test is sadly failing with: ```../../src/runtime/capi.cpp:569: int PyObject_IsTrue(PyObject *): Fatal Python error: unimplemented```
which is strange...

**Pull request closed without merging**
