### PR TITLE
SmallArena alloc with binary search

### PR DESCRIPTION
**Pull request by corona10**
Little effect , but it became a little more quickly .

### CODE REVIEW

**Comment by rudi-c** [comment]
Have you measured what the performance change is?

**Comment by Daetalus** [comment]
FIY, https://github.com/dropbox/pyston/blob/master/docs/TIPS.md#benchmarks may could help.

**Comment by corona10** [comment]
@rudi-c  when i run
```

 'python ../pyston-perf/benchmarking/measure_perf.py --save baseline --run-times 3 --take-min'
```
 what should i do??

```

Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
              pyston pyxl_bench.py                      : failed (code 1)
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
              pyston sqlalchemy_imperative2.py          : failed (code 1)


```

**Comment by corona10** [comment]
@rudi-c  @Daetalus 
when i run bench test it occured import error

```
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
              pyston pyxl_bench.py                      : failed (code 1)
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy

```

what should i do?

**Comment by corona10** [comment]
@rudi-c @Daetalus 

when i run benchmark it occured like this

```
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/pyxl_bench.py", line 6, in <module>:
    from pyxl.codec.register import pyxl_transform_string
ImportError: No module named pyxl.codec.register
              pyston pyxl_bench.py                      : failed (code 1)
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "../pyston-perf/benchmarking/benchmark_suite/sqlalchemy_imperative2.py", line 5, in <module>:
    from sqlalchemy import Column, ForeignKey, Integer, String, Table, MetaData
ImportError: No module named sqlalchemy
              pyston sqlalchemy_imperative2.py          : failed (code 1)

```

i install pyxl with pyston_release setup.py install and it import instantly.
but when i run test it failed..

**Comment by rudi-c** [comment]
In pyston-perf, did you do `git submodule update --init --recursive`?

**Comment by corona10** [comment]
@rudi-c thanks i did it!
```
Comparing to '['baseline']'
              pyston (calibration)                      :   1.16s baseline: 1.16 ( -0.1%)
              pyston django_template3.py                :   3.52s baseline: 3.68 ( -4.2%)
              pyston pyxl_bench.py                      :   2.27s baseline: 2.36 ( -3.8%)
              pyston sqlalchemy_imperative2.py          :   3.20s baseline: 4.05 (-21.1%)
              pyston django_template3_10x.py            :  22.41s baseline: 23.18 ( -3.3%)
              pyston pyxl_bench_10x.py                  :  16.16s baseline: 16.17 ( -0.1%)
              pyston sqlalchemy_imperative2_10x.py      :  24.10s baseline: 23.27 (  3.6%)
              pyston (geomean-2ec9)                     :   2.95s baseline: 3.28 (-10.1%)
```

**Comment by undingen** [comment]
It looks like the baseline stats you were comparing too are an older version.
Because I tried to reproduce it with 
```python analysis/investigate.py 345326260f707c7fc7aa3ad3a19e721ce1490a10 748585d63d3ca88924c8b13e49c38582f09bf1ad```

and got the following output:
```
                                345326260f707c7fc7:  748585d63d3ca88924:
           django_template3.py             2.8s (4)             2.8s (4)  +0.5%
                 pyxl_bench.py             2.2s (4)             2.3s (4)  +0.8%
     sqlalchemy_imperative2.py             2.8s (4)             2.8s (4)  +0.9%
                       geomean                 2.6s                 2.6s  +0.7%
```
So sadly it's a small slowdown instead of a speedup :-(

**Comment by corona10** [comment]
@undingen  no my master branch is up to date with dropbox master
and i run multiple times and almost same result. and i can not understand why binary search can be slow than linear search when data set is over 20s?

**Comment by Daetalus** [comment]
Just a theoretically answer about why it slow (not verify it) : 20s doesn't mean the time was costed on this operation. Maybe just call it many times, but each time the `NUM_BUCKETS` is small.

**Comment by undingen** [comment]
I'm not sure but maybe we often wont't need one of the larger sizes or we have some fixed size objects which are larger than 32 bytes and with the binary search the compiler maybe unable to determine at compile time the bucket it should go too???
I'm also not sure if a binary search is fast for 18 elements than a very small loop.

**Comment by corona10** [comment]
@undingen  okay, binary search is not always faster than linear search that what kinds of data set requested..
but i tested it 12000 requests for small byte in random data set and the result was binary search is very very little bit faster. and i also agree with that that kinds of circumstance is very rare.
and +/- 1~2% is can be affected by testing circumstance likes cache or something else.

and i know my PR is not meaningful code.

**Comment by undingen** [comment]
But it was worth a try :-)

**Comment by corona10** [comment]
@kmod same thinking?? than i will closed this PR

**Comment by kmod** [comment]
Yeah there might be some improvements that can be made here but it's definitely not an easy thing :/
I would guess the most important thing perf-wise is the compiler being able to statically determine which bucket a constant-size allocation belongs to; I don't think it can do that for either the linear scan or the binary search, but increasing the size of this function might make the compiler decide to not inline it which is probably larger of an effect than the linear-vs-binary-search change.

The assembly for the linear-scan version also looks very efficient: the compiler fully unrolls the loop and fully resolves the `size[]` accesses to constants, so there are no memory accesses or anything.  We might be able to get a very slight improvement by changing the linear sequence of checks to a binary tree (or maybe do one bisection and then a linear sequence), but we would probably need to write it in a way that doesn't become a loop+memory accesses.  And the benefit would probably be small.

**Pull request closed without merging**
